# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Jukebox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Jukebox.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rJukebox.proto\"\x8d\x03\n\x07Jukebox\x12\x1f\n\x06\x61rtist\x18\x01 \x03(\x0b\x32\x0f.Jukebox.Artist\x1a\xe0\x02\n\x06\x41rtist\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05\x61lbum\x18\x02 \x03(\x0b\x32\x15.Jukebox.Artist.Album\x1a\xa1\x02\n\x05\x41lbum\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x05genre\x18\x02 \x01(\x0e\x32 .Jukebox.Artist.Album.genre_list\x12\x0c\n\x04year\x18\x03 \x01(\r\x12\x31\n\x06lineup\x18\x04 \x03(\x0b\x32!.Jukebox.Artist.Album.LineupEntry\x12\r\n\x05title\x18\x05 \x03(\t\x1a-\n\x0bLineupEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Z\n\ngenre_list\x12\t\n\x05\x64ummy\x10\x00\x12\x08\n\x04rock\x10\x01\x12\x07\n\x03pop\x10\x02\x12\x0f\n\x0b\x61lternative\x10\x03\x12\x0b\n\x07\x63lassic\x10\x04\x12\x10\n\x0c\x65xperimental\x10\x05\x62\x06proto3'
)



_JUKEBOX_ARTIST_ALBUM_GENRE_LIST = _descriptor.EnumDescriptor(
  name='genre_list',
  full_name='Jukebox.Artist.Album.genre_list',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='dummy', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='rock', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='pop', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='alternative', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='classic', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='experimental', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=325,
  serialized_end=415,
)
_sym_db.RegisterEnumDescriptor(_JUKEBOX_ARTIST_ALBUM_GENRE_LIST)


_JUKEBOX_ARTIST_ALBUM_LINEUPENTRY = _descriptor.Descriptor(
  name='LineupEntry',
  full_name='Jukebox.Artist.Album.LineupEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Jukebox.Artist.Album.LineupEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Jukebox.Artist.Album.LineupEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=323,
)

_JUKEBOX_ARTIST_ALBUM = _descriptor.Descriptor(
  name='Album',
  full_name='Jukebox.Artist.Album',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Jukebox.Artist.Album.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Jukebox.Artist.Album.genre', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year', full_name='Jukebox.Artist.Album.year', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lineup', full_name='Jukebox.Artist.Album.lineup', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='Jukebox.Artist.Album.title', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JUKEBOX_ARTIST_ALBUM_LINEUPENTRY, ],
  enum_types=[
    _JUKEBOX_ARTIST_ALBUM_GENRE_LIST,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=415,
)

_JUKEBOX_ARTIST = _descriptor.Descriptor(
  name='Artist',
  full_name='Jukebox.Artist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Jukebox.Artist.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='album', full_name='Jukebox.Artist.album', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JUKEBOX_ARTIST_ALBUM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=415,
)

_JUKEBOX = _descriptor.Descriptor(
  name='Jukebox',
  full_name='Jukebox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='artist', full_name='Jukebox.artist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JUKEBOX_ARTIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=415,
)

_JUKEBOX_ARTIST_ALBUM_LINEUPENTRY.containing_type = _JUKEBOX_ARTIST_ALBUM
_JUKEBOX_ARTIST_ALBUM.fields_by_name['genre'].enum_type = _JUKEBOX_ARTIST_ALBUM_GENRE_LIST
_JUKEBOX_ARTIST_ALBUM.fields_by_name['lineup'].message_type = _JUKEBOX_ARTIST_ALBUM_LINEUPENTRY
_JUKEBOX_ARTIST_ALBUM.containing_type = _JUKEBOX_ARTIST
_JUKEBOX_ARTIST_ALBUM_GENRE_LIST.containing_type = _JUKEBOX_ARTIST_ALBUM
_JUKEBOX_ARTIST.fields_by_name['album'].message_type = _JUKEBOX_ARTIST_ALBUM
_JUKEBOX_ARTIST.containing_type = _JUKEBOX
_JUKEBOX.fields_by_name['artist'].message_type = _JUKEBOX_ARTIST
DESCRIPTOR.message_types_by_name['Jukebox'] = _JUKEBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Jukebox = _reflection.GeneratedProtocolMessageType('Jukebox', (_message.Message,), {

  'Artist' : _reflection.GeneratedProtocolMessageType('Artist', (_message.Message,), {

    'Album' : _reflection.GeneratedProtocolMessageType('Album', (_message.Message,), {

      'LineupEntry' : _reflection.GeneratedProtocolMessageType('LineupEntry', (_message.Message,), {
        'DESCRIPTOR' : _JUKEBOX_ARTIST_ALBUM_LINEUPENTRY,
        '__module__' : 'Jukebox_pb2'
        # @@protoc_insertion_point(class_scope:Jukebox.Artist.Album.LineupEntry)
        })
      ,
      'DESCRIPTOR' : _JUKEBOX_ARTIST_ALBUM,
      '__module__' : 'Jukebox_pb2'
      # @@protoc_insertion_point(class_scope:Jukebox.Artist.Album)
      })
    ,
    'DESCRIPTOR' : _JUKEBOX_ARTIST,
    '__module__' : 'Jukebox_pb2'
    # @@protoc_insertion_point(class_scope:Jukebox.Artist)
    })
  ,
  'DESCRIPTOR' : _JUKEBOX,
  '__module__' : 'Jukebox_pb2'
  # @@protoc_insertion_point(class_scope:Jukebox)
  })
_sym_db.RegisterMessage(Jukebox)
_sym_db.RegisterMessage(Jukebox.Artist)
_sym_db.RegisterMessage(Jukebox.Artist.Album)
_sym_db.RegisterMessage(Jukebox.Artist.Album.LineupEntry)


_JUKEBOX_ARTIST_ALBUM_LINEUPENTRY._options = None
# @@protoc_insertion_point(module_scope)
